name: Profile Readme Development Stats

on:
  schedule:
    # Runs at 11:00 am SGT
    - cron: '30 01 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: TRUE
          SHOW_SHORT_INFO: TRUE
          SHOW_PROFILE_VIEWS: TRUE
          SHOW_LOC_CHART:  TRUE
          SHOW_PROJECTS:  FALSE
